# Generated by Django 4.2.4 on 2024-05-05 08:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='No Title')),
                ('content', models.TextField(default='No Content')),
                ('time', models.DateTimeField(default=datetime.datetime(2024, 5, 5, 13, 38, 41, 391208))),
                ('tags', models.TextField(default='Blog')),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2024, 5, 5, 13, 38, 41, 391208))),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('time', models.DateTimeField(default=datetime.datetime(2024, 5, 5, 13, 38, 41, 391208))),
                ('last_updated', models.DateTimeField(default=datetime.datetime(2024, 5, 5, 13, 38, 41, 391208))),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('blog_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogging.blogs')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
