# Generated by Django 4.2.4 on 2024-06-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0002_alter_blogs_last_updated_alter_blogs_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='userDisLiked',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='blogs',
            name='userLiked',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='last_updated',
            field=models.CharField(default='2024-06-11 23:48:14.351237', max_length=40),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='time',
            field=models.CharField(default='2024-06-11 23:48:14.350241', max_length=40),
        ),
        migrations.AlterField(
            model_name='comments',
            name='last_updated',
            field=models.CharField(default='2024-06-11 23:48:14.351237', max_length=40),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.CharField(default='2024-06-11 23:48:14.351237', max_length=40),
        ),
    ]
