# Generated by Django 4.2.4 on 2024-05-03 06:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogging', '0003_blogs_last_updated_alter_blogs_time_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogs',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blogs',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 11, 43, 5, 8120)),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 11, 43, 5, 8120)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='last_updated',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 11, 43, 5, 9116)),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 3, 11, 43, 5, 9116)),
        ),
    ]
