# Generated by Django 4.2.4 on 2024-06-20 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0006_alter_blogs_last_updated_alter_blogs_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='userDisLiked',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='comments',
            name='userLiked',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='last_updated',
            field=models.CharField(default='2024-06-20 21:03:25.587910', max_length=40),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='tags',
            field=models.TextField(blank=True, default='Blog'),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='time',
            field=models.CharField(default='2024-06-20 21:03:25.587910', max_length=40),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='userDisLiked',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='userLiked',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='comments',
            name='last_updated',
            field=models.CharField(default='2024-06-20 21:03:25.587910', max_length=40),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.CharField(default='2024-06-20 21:03:25.587910', max_length=40),
        ),
    ]
