# Generated by Django 4.2.4 on 2024-06-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0007_comments_userdisliked_comments_userliked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='userDisLiked',
        ),
        migrations.RemoveField(
            model_name='blogs',
            name='userLiked',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='userDisLiked',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='userLiked',
        ),
        migrations.AlterField(
            model_name='blogs',
            name='last_updated',
            field=models.CharField(default='2024-06-20 21:21:28.992450', max_length=40),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='time',
            field=models.CharField(default='2024-06-20 21:21:28.992450', max_length=40),
        ),
        migrations.AlterField(
            model_name='comments',
            name='last_updated',
            field=models.CharField(default='2024-06-20 21:21:28.993453', max_length=40),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.CharField(default='2024-06-20 21:21:28.993453', max_length=40),
        ),
    ]
