# Generated by Django 4.2.4 on 2024-06-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0008_remove_blogs_userdisliked_remove_blogs_userliked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='last_updated',
            field=models.CharField(default='2024-06-21 00:10:47.472282', max_length=40),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='time',
            field=models.CharField(default='2024-06-21 00:10:47.472282', max_length=40),
        ),
        migrations.AlterField(
            model_name='comments',
            name='last_updated',
            field=models.CharField(default='2024-06-21 00:10:47.472282', max_length=40),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.CharField(default='2024-06-21 00:10:47.472282', max_length=40),
        ),
    ]
