# Generated by Django 4.2.4 on 2024-06-21 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0009_alter_blogs_last_updated_alter_blogs_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='last_updated',
            field=models.CharField(default='2024-06-21 18:24:16.223406', max_length=40),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='time',
            field=models.CharField(default='2024-06-21 18:24:16.223406', max_length=40),
        ),
        migrations.AlterField(
            model_name='comments',
            name='last_updated',
            field=models.CharField(default='2024-06-21 18:24:16.226017', max_length=40),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.CharField(default='2024-06-21 18:24:16.226017', max_length=40),
        ),
    ]
