# Generated by Django 5.0.7 on 2024-07-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogging', '0010_blogs_blog_comments_alter_blogs_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='last_updated',
            field=models.CharField(default='2024-07-28 20:59:44.945447', max_length=40),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='time',
            field=models.CharField(default='2024-07-28 20:59:44.945447', max_length=40),
        ),
        migrations.AlterField(
            model_name='comments',
            name='last_updated',
            field=models.CharField(default='2024-07-28 20:59:44.945447', max_length=40),
        ),
        migrations.AlterField(
            model_name='comments',
            name='time',
            field=models.CharField(default='2024-07-28 20:59:44.945447', max_length=40),
        ),
    ]
