# Generated by Django 4.2.4 on 2024-06-12 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicDetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserdetails',
            name='disliked_blogs',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuserdetails',
            name='disliked_comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='customuserdetails',
            name='liked_comments',
            field=models.TextField(default=''),
        ),
    ]
