# Generated by Django 4.2.4 on 2024-06-13 10:11

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicDetails', '0002_customuserdetails_disliked_blogs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuserdetails',
            name='followed_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
