# Generated by Django 4.2.4 on 2024-06-20 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicDetails', '0003_customuserdetails_followed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserdetails',
            name='disliked_blogs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customuserdetails',
            name='disliked_comments',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customuserdetails',
            name='interests',
            field=models.TextField(blank=True, default='AI[<#SEP#>]ML[<#SEP#>]Robotics'),
        ),
        migrations.AlterField(
            model_name='customuserdetails',
            name='liked_blogs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='customuserdetails',
            name='liked_comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
