# Generated by Django 4.2.4 on 2024-06-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BasicDetails', '0004_alter_customuserdetails_disliked_blogs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserdetails',
            name='interests',
            field=models.TextField(blank=True, default='BlogSite, Blogging'),
        ),
    ]
